export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_CATALOG = 'CREATE_CATALOG';
export const DELETE_CATALOG = 'DELETE_CATALOG';
export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOGS = 'FETCH_CATALOGS';
export const EDIT_CATALOG = 'EDIT_CATALOG';

export const FETCH_PAGE_COUNT = 'FETCH_PAGE_COUNT';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';

export const ADD_SORTING_CRITERIA_SORT_BY = 'ADD_SORTING_CRITERIA_SORT_BY';
export const ADD_SORTING_CRITERIA_SORT_TYPE = 'ADD_SORTING_CRITERIA_SORT_TYPE';

export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';