export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';



export const CREATE_CATALOG = 'CREATE_CATALOG';
export const DELETE_CATALOG = 'DELETE_CATALOG';
export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOGS = 'FETCH_CATALOGS';
export const EDIT_CATALOG = 'EDIT_CATALOG';

export const ADD_COURSE_TO_CATALOG = 'ADD_COURSE_TO_CATALOG';
export const REMOVE_COURSE_FROM_CATALOG = 'REMOVE_COURSE_FROM_CATALOG';

export const FETCH_CATALOG_PAGE_COUNT = 'FETCH_CATALOG_PAGE_COUNT';
export const SET_CATALOG_OFFSET = 'SET_CATALOG_OFFSET';
export const SET_CATALOG_PAGE_SIZE = 'SET_CATALOG_PAGE_SIZE';

export const ADD_CATALOG_SORTING_CRITERIA_SORT_BY = 'ADD_CATALOG_SORTING_CRITERIA_SORT_BY';
export const ADD_CATALOG_SORTING_CRITERIA_SORT_TYPE = 'ADD_CATALOG_SORTING_CRITERIA_SORT_TYPE';

export const CATALOG_SEARCH_KEYWORD = 'CATALOG_SEARCH_KEYWORD';



export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';

export const FETCH_COURSE_PAGE_COUNT = 'FETCH_COURSE_PAGE_COUNT';
export const SET_COURSE_OFFSET = 'SET_COURSE_OFFSET';
export const SET_COURSE_PAGE_SIZE = 'SET_COURSE_PAGE_SIZE';

export const ADD_COURSE_SORTING_CRITERIA_SORT_BY = 'ADD_COURSE_SORTING_CRITERIA_SORT_BY';
export const ADD_COURSE_SORTING_CRITERIA_SORT_TYPE = 'ADD_COURSE_SORTING_CRITERIA_SORT_TYPE';

export const COURSE_SEARCH_KEYWORD = 'COURSE_SEARCH_KEYWORD';




export const FETCH_PATRON = 'FETCH_PATRON';
export const FETCH_PATRONS = 'FETCH_PATRONS';
export const EDIT_PATRON = 'EDIT_PATRON';

export const FETCH_PATRON_PAGE_COUNT = 'FETCH_PATRON_PAGE_COUNT';
export const SET_PATRON_OFFSET = 'SET_PATRON_OFFSET';
export const SET_PATRON_PAGE_SIZE = 'SET_PATRON_PAGE_SIZE';

export const ADD_PATRON_SORTING_CRITERIA_SORT_BY = 'ADD_PATRON_SORTING_CRITERIA_SORT_BY';
export const ADD_PATRON_SORTING_CRITERIA_SORT_TYPE = 'ADD_PATRON_SORTING_CRITERIA_SORT_TYPE';

export const PATRON_SEARCH_KEYWORD = 'PATRON_SEARCH_KEYWORD';




